// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccount = "accounts"

// Account mapped from table <accounts>
type Account struct {
	ID       string `gorm:"column:id;not null" json:"id"`
	Nickname string `gorm:"column:nickname" json:"nickname"`
	Phone    string `gorm:"column:phone" json:"phone"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
