// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFriend = "friends"

// Friend mapped from table <friends>
type Friend struct {
	ID       string `gorm:"column:id" json:"id"`
	Nickname string `gorm:"column:nickname" json:"nickname"`
	Owner    string `gorm:"column:owner" json:"owner"`
}

// TableName Friend's table name
func (*Friend) TableName() string {
	return TableNameFriend
}
