// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGroup = "groups"

// Group mapped from table <groups>
type Group struct {
	ID    string `gorm:"column:id" json:"id"`
	Name  string `gorm:"column:name" json:"name"`
	Type  int32  `gorm:"column:type" json:"type"`
	Owner string `gorm:"column:owner" json:"owner"`
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
